---
openapi: 3.0.2
info:
  title: NLP API
  version: 1.0.0
  description: An API to expose the NLP Engine that enhance unstructured text
  contact:
    name: Catalogue of Services Team
    url: https://github.com/catalogue-of-services-isa
    email: isa2@ec.europa.eu
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
servers:
- url: http://35.181.155.22:5000/api
paths:
  /canEnhance:
    summary: check if the NLP engine is busy
    get:
      tags:
      - metatags
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
              examples:
                Response Example:
                  value:
                    status: true
          description: Return the status
      operationId: can_Enhance
      x-openapi-router-controller: nlp_api.web.controllers.enhance_controller
      description: return the status of the NLP engine
  /enhance:
    summary: ask the NLP engine if it can enhance the unstructured text
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnhanceRequest'
        required: true
      tags:
      - metatags
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnhanceResponse'
          description: the response of the NLP engine
      operationId: enhance
      x-openapi-router-controller: nlp_api.web.controllers.enhance_controller
      description: send the request to enhance
components:
  schemas:
    EnhanceResponse:
      title: Root Type for EnhanceResponse
      description: the response of the NLP engine
      required:
      - metatags
      type: object
      properties:
        metatags:
          description: Array of metatags
          type: array
          items:
            $ref: '#/components/schemas/MetaTag'
          example:
          - name: DC.ISO3166
            value: IT
    MetaTag:
      title: Root Type for MetaTag
      description: a metatag has a name and a value
      required:
      - name
      - value
      type: object
      properties:
        name:
          description: the name of the metatag
          type: string
          example: '"DC.ISO3166"'
        value:
          description: the value of the metatag
          type: string
          example: '"IT"'
    Status:
      description: Status of the NLP engine
      required:
      - status
      type: object
      properties:
        status:
          description: "the status of the NLP engine, true if the engine is available\
            \ false otherwise"
          type: boolean
          example: true
    EnhanceRequest:
      title: Root Type for EnhanceRequest
      description: The request for the NLP engine to enhance text
      required:
      - metatags
      - text
      - url
      type: object
      properties:
        metatags:
          description: the list of metatags to be extracted from the text
          type: array
          items:
            type: string
        url:
          description: the URL of the webpage containing the text
          type: string
        text:
          description: the text to be enhanced with metatags
          type: string
tags:
- name: metatags
  description: NLP engine function about dealing with metatags
